= PoolDesigner - Designing Multiplexed Pools for Assembling Library Constructs

== Quickstart

. Clone this project from GitHub.
. http://neo4j.com/download[Download, install, and start a Neo4j server.].
. Open the Neo4j web interface in your browser at http://localhost:7474.
. Configure "*kn0x*" as the Neo4j password.
. https://maven.apache.org/download.cgi[Download and install Maven.]
. Build and run this project from the command line with `mvn spring-boot:run`.
. Open the Pool Designer web interface in your browser at http://localhost:8080.
. Quick demo: 
. Click Choose Files and select nif_library.xml from the directory poolDesigner/src/main/resources/static/sbol/.
. Click Import SBOL to load the construct library into Neo4j.
. Click New Structure to create a new pool structure and change 'CDS' to 'nifY'.
. Click Extract Pools to automatically design a new pool based on your structure.

== License

Copyright (c) 2016, Nicholas Roehner
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided 
that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and 
the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions 
and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse 
or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED 
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A 
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR 
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED 
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
THE POSSIBILITY OF SUCH DAMAGE.
